### ISSUE TITLE
Catsequences did not install

### ISSUE THREAD

**Issue by Enhancer01** [ChrisCreevey/catsequences#2]
I downloaded this script from github on my vagrant VM and SSH server. both are having similar issues with installation. i followed your instruction to install using this command  "cc catsequences.c -o catsequences -lm"; i however, kept getting this message instead. any help please?

catsequences.c: In function ‘main’:
catsequences.c:35:37: warning: comparison between pointer and zero character constant [-Wpointer-compare]
  if((infile1 = fopen(argv[1], "r")) == '\0')   /* check to see if the file is there */
                                     ^~
catsequences.c:35:5: note: did you mean to dereference the pointer?
  if((infile1 = fopen(argv[1], "r")) == '\0')   /* check to see if the file is there */
     ^
catsequences.c:71:39: warning: comparison between pointer and zero character constant [-Wpointer-compare]
   if((infile2 = fopen(filename, "r")) == '\0')   /* check to see if the file is there */
                                       ^~
catsequences.c:71:6: note: did you mean to dereference the pointer?
   if((infile2 = fopen(filename, "r")) == '\0')   /* check to see if the file is there */
      ^

**Comment by ChrisCreevey** [comment]
Thanks for pointing this out, these warnings would not have stopped the compilation of the software, but I've adjusted the code to remove them so as not to cause confusion. See latest commit.

**Comment by Enhancer01** [comment]
I deleted the previous and re-clone the git. It worked perfectly. In fact, It was so fast that I almost doubt if it actually did the right thing. It concatenate more than 14,000 fas files in less than one minute, I haven't seen any script this fast.

Thank you very much
